name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-4.2.1-bazel-cache

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Build lib
        run: bazel build //src:imgui_info_center
      
      - name: Build example
        run: bazel build //example:info_center_example